# syntax=docker/dockerfile:1.7
FROM golang:1.25-alpine

RUN apk add --no-cache git

ENV GOTOOLCHAIN=auto
ENV GOSUMDB=off
ENV GOPROXY=https://proxy.golang.org,direct

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go install github.com/air-verse/air@v1.61.7

WORKDIR /app

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
